ERRMOT.LS      Robot Name ROBOT 11-APR-23 12:42:54  

1" 08-APR-23 14:47:22 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
2" 08-APR-23 14:10:54 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
3" 08-APR-23 12:46:56 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
4" 08-APR-23 11:48:22 " SRVO-307 HBK close/HBK enabled (G:1)              " " WARN                          00000000" 
