ERRMOT.LS      Robot Name ROBOT 22-APR-23 19:44:08  

1" 11-APR-23 12:55:00 " MOTN-056 Speed limits used (G:1)                  " DATA     0   2   0    0   0        1              " NONE                          10000000" 
2" 11-APR-23 12:53:18 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
3" 08-APR-23 14:47:22 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
4" 08-APR-23 14:10:54 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
5" 08-APR-23 12:46:56 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
6" 08-APR-23 11:48:22 " SRVO-307 HBK close/HBK enabled (G:1)              " " WARN                          00000000" 
