ERRMOT.LS      Robot Name ROBOT 11-APR-23 12:42:50  

1" 08-APR-23 14:51:00 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
2" 08-APR-23 14:47:48 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
3" 08-APR-23 14:47:12 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
4" 08-APR-23 14:10:12 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
5" 01-APR-23 14:35:56 " SRVO-307 HBK close/HBK enabled (G:1)              " " WARN                          00000000" 
