ERRAPP.LS      Robot Name ROBOT 22-APR-23 19:44:04  

1" 15-APR-23 11:33:22 " APSH-155 HOME position not recorded               " APSH-156 Specify Home in Ref Pos Menu             " WARN                          00000000" 
2" 08-APR-23 11:15:58 " APSH-155 HOME position not recorded               " APSH-156 Specify Home in Ref Pos Menu             " WARN                          00000000" 
3" 01-APR-23 14:35:58 " APSH-155 HOME position not recorded               " APSH-156 Specify Home in Ref Pos Menu             " WARN                          00000000" 
